make energy metrics as input variables
fmperf-project/fmperf pull request #8
Opened 2024-05-31 07:44 UTC by rinana

#7 this change enables users to change the metrics to pull from Prometheus by specifying a yaml file of metrics list.
The default metrics will be used unless it is specified.

2024-05-31 17:19 UTC, yuezhu1 commented
Hi @rinana , Would you mind assigning me as the code reviewer?

2024-05-31 17:37 UTC, yuezhu1 commented on fmperf/loadgen/collect_energy.py
> +        all_df.columns.extend(mlist)
will this only work when `mlist` is not None?

2024-05-31 17:44 UTC, yuezhu1 commented on fmperf/loadgen/collect_energy.py
> +             metrics.extend(mlist)
directly extending `metrics` column name by `mlist` can cause redundant column name. The default `metrics` already contain `kepler_container_gpu_joules_total`, `kepler_container_package_joules_total`, and `kepler_container_dram_joules_total`. However, in your `fmperf/loadgen/default_metrics.yaml`, these three are also included. Consider checking if the column name wanted to add is unique before adding a new column name

2024-05-31 17:45 UTC, yuezhu1 commented on fmperf/loadgen/collect_energy.py
>              "dcgm_energy",
we also want to indicate that the energy/power here is the total energy/power, or dynamic energy/power, since we already mentioned `dcgm_idle_power`

2024-05-31 23:24 UTC, rinana commented on fmperf/loadgen/collect_energy.py
> +    metric_list = os.environ.get('TARGET_METRICS_LIST', 'default_metrics.yaml')
@yuezhu1 We can avoid rebuild new image, by setting a file path for metrics list to this environment variable.

2024-06-03 20:49 UTC, yuezhu1 requested changes
The changes mostly look good. only `get_target_metrics()` needs some additional work to make sure that every new metric added in is unique. This could prevent potential issue when accidentally having redundant metrics been put in the list.

2024-06-05 14:02 UTC, yuezhu1 approved these changes
lgtm. Thanks for making the changes!

2024-06-06 18:54 UTC, tdoublep commented
@rinana @yuezhu1 invited you both as collaborators - please accept then it should be possible for you to merge the PR

2024-06-07 08:00 UTC, merged